services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=WF2
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - C:\docker_composer:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: worldfit_container
    ports:
      - 8080:8080
    environment:
      db_url: jdbc:postgresql://db:5432/WF2
      db_username: postgres
      db_password: admin
    depends_on:
      - db
    restart: always
